angryexception/__init__.py,sha256=ujOOguqnX057kcQf8VJixtoOeOy1pV3miNSPl02ORQI,1022
angryexception-1.0.0.dist-info/WHEEL,sha256=y3eDiaFVSNTPbgzfNn0nYn5tEn1cX6WrdetDlQM4xWw,83
angryexception-1.0.0.dist-info/METADATA,sha256=zaFYvFabBLF6skVzbXTrAplT9JPrvS3TgSsg0E73OHA,762
angryexception-1.0.0.dist-info/RECORD,,
